<FeatSelector@BoxLayout>:
    orientation:'horizontal'
    Label:
        id: featlabel
        text: 'Feat:'
    Button:
        id: featbutton
        on_release: root.open_feat_popup()
#    Button:
#        id: featinfobutton
#        text: 'Info'

FeatScreen:
    name: 'General Tab'
    fullscreen: True
    ScrollView:
        BoxLayout:
            id: featcontainer
            size_hint_y:None
            height:sum(x.height for x in self.children)
            orientation:'vertical'